spring.application.name=wagonmanager
server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=pgpwd4habr
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog-root.xml
logging.level.liquibase = DEBUG
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
